### ISSUE TITLE
게시글 작성, 삭제, 수정 등 관련 구현

### ISSUE THREAD

**Issue by bagger3025** [osamhack2022/WEB_MiliDream_Dreamers#14]
board, career로 노션 페이지에 있는 대로 일단 구현했습니다.

**Comment by Seonwu-K** [comment]
- [x] 더미데이터 만들 수 있도록 base.sql 수정 

기존 base.sql에 table만 생성하고 데이터가 없었기 때문에 더미 데이터를 작성해두었습니다.
기존 db 삭제 후 갱신하시기 귀찮으시면 그냥
base.sql 맨 밑에 insert문 2개를 사용하시고 select 하셔서 아래와 같은 결과가 나오는지 확인해주시면 됩니다.

![image](https://user-images.githubusercontent.com/60039286/193606559-926ece30-7b3a-4919-bf5b-cdcbba516ae9.png)
![image](https://user-images.githubusercontent.com/60039286/193606460-d657fe0b-bbfc-462d-8d4e-080a4f9e18d3.png)

- [ ] 카테고리 정확히 무엇이 있는지 정리해서 category id 값 fix하기
- [x] Post 데이터 GET요청 구현하기 
- [x] Post 데이터 POST요청 로직(글 생성) 구현하기
- [x] Post 데이터 DELETE요청 로직 구현하기

**Comment by meoraeng** [comment]
기능을 먼저 구현하고 저희 파일 구조에 맞춰서 models, service 분리하는 작업을 추후 따로 하겠습니다

**Comment by bagger3025** [comment]
Recommend를 제외한 모든 Post 관련 모델, 서비스, 라우팅 수정은 backend-feat-carrer 브랜치에서만 하도록 하겠습니다.

**Comment by bagger3025** [comment]
개발이 완료되었다고 판단하므로 이슈 종료하겠습니다.
백엔드 관련해서 나오는 이슈는 새로 등록해주시기 바랍니다.
