### ISSUE TITLE
Directory Setting

### ISSUE THREAD

**Issue by Seonwu-K** [osamhack2022/WEB_MiliDream_Dreamers#3]
3 layer architecture 기반 backend 디렉토리 세팅 및 필요한 기본 세팅 파일 작성

**Comment by Seonwu-K** [comment]
- [x] 백엔드 디렉토리명  변경: expressapp -> backend
- [x] 3-layer-architecture 기반 디렉토리 구조 세팅
- [x] loader 디렉토리 필수 미들웨어 세팅

**Comment by Seonwu-K** [comment]
- [x] nodemon 세팅
- [x] eslint 세팅
- [x] method-override 세팅
- [x] helmet
- [x] express.json

**Comment by Seonwu-K** [comment]
- [x] 추가 폴더 생성(subscriber, services)
- [x] readme directory structure 수정

여기까지가 db 연결 전 할 수 있는 세팅 전부인 듯 합니다.
추가로 필요한 미들웨어 등은 이제 새로운 이슈를 열어서 세팅하면 될 것 같습니다.

**Comment by bagger3025** [comment]
prettier도 있으면 좋을 것 같아 추가합니다.
eslint와 prettier가 저장할 때 작동할 수 있도록 .vscode 폴더 내의 settings.json 추가했습니다.

**Comment by Seonwu-K** [comment]
이제 기본 세팅은 거의 완성된 듯 하여 이슈를 닫고 브랜치를 지우도록 하겠습니다.
이제부터 추가로 필요한 미들웨어나 라이브러리는 개발 기능과 연관된 경우가 대부분일 것으로 예상되어
그때 새로운 이슈와 브랜치를 열고 다루면 될 것 같습니다
