### ISSUE TITLE
서버 배포 && 절대 경로 img, back api 오류

### ISSUE THREAD

**Issue by Turtle-Hwan** [osamhack2022/WEB_MiliDream_Dreamers#57]

**Comment by inyeoptti** [comment]
gh-pages 배포하였으나 절대 경로로 되어 있는 이미지 파일은 깨져서 보입니다
![image](https://user-images.githubusercontent.com/48206925/196192587-493f6f46-8ea5-4b64-acc5-295f298733df.png)

**Comment by Turtle-Hwan** [comment]
## 이유 알아낸 거 같습니다!!
* github.io 특성상
주어진 url이 `https://osamhack2022.github.io/WEB_MiliDream_Dreamers/` 까지인데, 

* `<img />` 태그 안에서는 `https://osamhack2022.github.io`를 root 경로로 인식하고 이 뒤에  나머지 url을 붙여버려서 오류나는 것이네요..

* 원래 이미지의 정적 경로는 `https://osamhack2022.github.io/WEB_MiliDream_Dreamers/` 요거 뒤에 붙이면 잘 나옵니다.
  * 예로, `https://osamhack2022.github.io/WEB_MiliDream_Dreamers/img/home/intro_1.svg`라는 url을 치면 빌드되어 올라간 이미지가 보입니다.

* frontend/component/board-center.js 에서와 같이 next에서 제공해주는 `<Image />` 태그를 쓰면 next.config.js에 있는 절대경로 추가값에 영향 받는지 이미지가 잘 나오는 거 같습니다. (f12로 봤을 때 WEB_MiliDream_Dreamers/ 요고 추가된 절대 경로로 나오구요..)

**Comment by Turtle-Hwan** [comment]
* 마찬가지 오류로, 
상단 GNB 메뉴 클릭하면 routing은 제대로 넘어가지는데, 
user 화면에서 브라우저 주소창에는 `https://osamhack2022.github.io/board` 요러한 경로로 (/레포네임 이 빠진) 보여지는 오류가 있네요.

* 이러한 경우, 새로고침을 한 번 누르면 github page 404가 뜹니당

* 비슷하게 해결 가능할 것 같은데.. .알아보겟습니다

**Comment by Turtle-Hwan** [comment]
next.config.js에 basePath 키-값 설정하는 것도 시도해볼만하네요

https://nextjs.org/docs/api-reference/next.config.js/basepath

현재 images 키가 설정된 상태라 <Image /> 태그는 잘 뜨는 것 같습니다

라고 할려고 했는데 벌써 올리셨네요 👍 👍

**Comment by Turtle-Hwan** [comment]
- <Image /> 태그 이용
- 배포를 Azure에서 진행
