### ISSUE TITLE
NavBar, footer, HOME 화면 생성 중

### ISSUE THREAD

**Issue by Seonwu-K** [osamhack2022/WEB_MiliDream_Dreamers#8]
해당 이슈가 어째선지 스크롤을 전부 차지해서 아이템을 추가할 수가 없네요 ..

![Image](https://user-images.githubusercontent.com/60039286/192816813-aa42c31a-4972-415e-839e-c2446c33db5b.png)

**Comment by Seonwu-K** [comment]
이제 보니 제가 새로 만든 이슈도 마찬가지네요.. 뭐가 문제일지..


.
.
.

문제점은 못찾았지만 라벨을 달면 해결됩니다. 라벨을 꼭 달아줍시다..

**Comment by sonyrainy** [comment]
아 그렇군요 감사합니다!
