### ISSUE TITLE
MariaDB install and connect server

### ISSUE THREAD

**Issue by Seonwu-K** [osamhack2022/WEB_MiliDream_Dreamers#9]
mariaDB 설치 및 초기 설정을 마친 후(해당 작업은 각자 컨테이너에서)
mariaDB 모듈을 통해 우리 서버와 연결하는 작업으로 진행됩니다.

**Comment by Seonwu-K** [comment]
- [x] mariaDB 설치
- [x] mariaDB 초기 세팅
- [x] mariaDB 모듈 설치
- [x] mariaDB 연결

**Comment by inyeoptti** [comment]
테스트 계정 생성 SQL
```sql
CREATE USER 'test'@'%' IDENTIFIED BY 'osam2022!@';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON  *.* TO 'test'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
flush privileges;
```

**Comment by meoraeng** [comment]
테스트 계정 password 해시값(SELECT password('osam2022!@') 결과값)
> *66C579693AED52873B03E849C8B46F03FB683A23

**Comment by Seonwu-K** [comment]
테스트 계정 password 해시값(SELECT password('osam2022!@') 결과값)

> *66C579693AED52873B03E849C8B46F03FB683A23

**Comment by bagger3025** [comment]
자동으로 DB 테이블 만들어주는 base.sql을 작성하였습니다.
`mysql -u test -p < base.sql`로 세팅해서 사용하시기 바랍니다.

**Comment by bagger3025** [comment]
자동으로 DB 테이블 만들어주는 base.sql을 작성하였습니다.
`mysql -u test -p < base.sql`로 세팅해서 사용하시기 바랍니다.
데이터베이스 이름은 millidream_db이고, notion의 DB 스키마 설계 페이지에 있는 내용을 그대로 옮겼습니다.

**Comment by Seonwu-K** [comment]
가시성 문제로 사용 안할 수도 있지만 getConnection() 에서 callback으로 
바로 relase query등이 사용 가능한 것으로 보여 수정하였습니다.

추가로 인엽 님의 제안대로 jsDoc를 도입해봤습니다.
